-- Migration: add_part_search_fields
-- Adds: Part.active, Part.barcode, Part.normalizedInternalCode
-- Drops: Part.internalCode unique global constraint (replaced by per-company unique)
-- Backfills: normalizedInternalCode from existing internalCode values
-- Creates: pg_trgm extension, GIN trigram indexes, and B-tree prefix fallback indexes

-- 1. Enable pg_trgm extension (idempotent)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Remove global unique constraint on internalCode (replaced by per-company unique below)
DROP INDEX IF EXISTS "Part_internalCode_key";

-- 3. Add new columns to Part table
ALTER TABLE "Part"
  ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "barcode" TEXT,
  ADD COLUMN "normalizedInternalCode" TEXT;

-- 4. Backfill normalizedInternalCode from existing internalCode values
UPDATE "Part"
SET "normalizedInternalCode" = lower(btrim("internalCode"))
WHERE "internalCode" IS NOT NULL;

-- 5. Per-company unique constraint on normalizedInternalCode (generated by Prisma @@unique)
CREATE UNIQUE INDEX "Part_companyId_normalizedInternalCode_key"
  ON "Part" ("companyId", "normalizedInternalCode");

-- 6. Composite index for filtering active parts by company
CREATE INDEX "part_company_active_idx"
  ON "Part" ("companyId", "active");

-- 7. GIN trigram indexes for partial/fuzzy search (requires pg_trgm)
CREATE INDEX "part_name_trgm_idx"
  ON "Part" USING gin ("name" gin_trgm_ops);

CREATE INDEX "part_brand_trgm_idx"
  ON "Part" USING gin ("brand" gin_trgm_ops);

CREATE INDEX "part_description_trgm_idx"
  ON "Part" USING gin ("description" gin_trgm_ops);

-- 8. B-tree functional indexes for prefix search fallback (without pg_trgm)
CREATE INDEX "part_company_name_prefix_idx"
  ON "Part" ("companyId", lower("name") text_pattern_ops);

CREATE INDEX "part_company_brand_prefix_idx"
  ON "Part" ("companyId", lower("brand") text_pattern_ops);

CREATE INDEX "part_company_manufacturer_prefix_idx"
  ON "Part" ("companyId", lower("manufacturerCode") text_pattern_ops);

-- 9. B-tree index for exact barcode lookup
CREATE INDEX "part_company_barcode_idx"
  ON "Part" ("companyId", "barcode");
