export enum Permission {
  SERVICE_ORDER_CREATE = 'SERVICE_ORDER_CREATE',
  SERVICE_ORDER_START = 'SERVICE_ORDER_START',
  SERVICE_ORDER_COMPLETE = 'SERVICE_ORDER_COMPLETE',
  SERVICE_ORDER_CANCEL = 'SERVICE_ORDER_CANCEL',
  SERVICE_ORDER_VIEW = 'SERVICE_ORDER_VIEW',

  STOCK_VIEW = 'STOCK_VIEW',
  STOCK_UPDATE = 'STOCK_UPDATE',

  FINANCIAL_VIEW = 'FINANCIAL_VIEW',
  FINANCIAL_CREATE = 'FINANCIAL_CREATE',

  AUDIT_VIEW = 'AUDIT_VIEW',

  USER_MANAGE = 'USER_MANAGE',
  COMPANY_SETTINGS = 'COMPANY_SETTINGS',
}

export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  MECHANIC = 'MECHANIC',
  FINANCE = 'FINANCE',
  RECEPTIONIST = 'RECEPTIONIST',
}
