export enum Permission {
  SERVICE_ORDER_CREATE = 'SERVICE_ORDER_CREATE',
  SERVICE_ORDER_START = 'SERVICE_ORDER_START',
  SERVICE_ORDER_DIAGNOSE = 'SERVICE_ORDER_DIAGNOSE',
  SERVICE_ORDER_COMPLETE = 'SERVICE_ORDER_COMPLETE',
  SERVICE_ORDER_CANCEL = 'SERVICE_ORDER_CANCEL',
  SERVICE_ORDER_VIEW = 'SERVICE_ORDER_VIEW',
  SERVICE_ORDER_ITEM_VIEW = 'SERVICE_ORDER_ITEM_VIEW',
  SERVICE_ORDER_ITEM_ADD = 'SERVICE_ORDER_ITEM_ADD',
  SERVICE_ORDER_ITEM_UPDATE = 'SERVICE_ORDER_ITEM_UPDATE',
  SERVICE_ORDER_ITEM_REMOVE = 'SERVICE_ORDER_ITEM_REMOVE',

  SERVICE_ORDER_APPROVAL_VIEW = 'SERVICE_ORDER_APPROVAL_VIEW',
  SERVICE_ORDER_APPROVAL_REQUEST = 'SERVICE_ORDER_APPROVAL_REQUEST',
  SERVICE_ORDER_APPROVAL_APPROVE = 'SERVICE_ORDER_APPROVAL_APPROVE',
  SERVICE_ORDER_APPROVAL_REJECT = 'SERVICE_ORDER_APPROVAL_REJECT',

  SERVICE_ORDER_EXECUTION_VIEW = 'SERVICE_ORDER_EXECUTION_VIEW',
  SERVICE_ORDER_EXECUTION_ASSIGN = 'SERVICE_ORDER_EXECUTION_ASSIGN',
  SERVICE_ORDER_EXECUTION_START = 'SERVICE_ORDER_EXECUTION_START',
  SERVICE_ORDER_EXECUTION_PAUSE = 'SERVICE_ORDER_EXECUTION_PAUSE',
  SERVICE_ORDER_EXECUTION_RESUME = 'SERVICE_ORDER_EXECUTION_RESUME',
  SERVICE_ORDER_EXECUTION_COMPLETE = 'SERVICE_ORDER_EXECUTION_COMPLETE',

  STOCK_VIEW = 'STOCK_VIEW',
  STOCK_UPDATE = 'STOCK_UPDATE',

  FINANCIAL_VIEW = 'FINANCIAL_VIEW',
  FINANCIAL_CREATE = 'FINANCIAL_CREATE',

  AUDIT_VIEW = 'AUDIT_VIEW',

  USER_MANAGE = 'USER_MANAGE',
  COMPANY_SETTINGS = 'COMPANY_SETTINGS',
}

export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  MECHANIC = 'MECHANIC',
  FINANCIAL = 'FINANCIAL',
  ATTENDANT = 'ATTENDANT',
  STOCKIST = 'STOCKIST',
}
