import { Role, Permission } from './permissions';

export const rolePermissions: Record<Role, Permission[]> = {
  [Role.ADMIN]: Object.values(Permission), // Admin has everything
  
  [Role.MANAGER]: [
    Permission.SERVICE_ORDER_VIEW,
    Permission.SERVICE_ORDER_ITEM_VIEW,
    Permission.SERVICE_ORDER_ITEM_ADD,
    Permission.SERVICE_ORDER_ITEM_UPDATE,
    Permission.SERVICE_ORDER_ITEM_REMOVE,
    Permission.SERVICE_ORDER_APPROVAL_VIEW,
    Permission.SERVICE_ORDER_APPROVAL_REQUEST,
    Permission.SERVICE_ORDER_APPROVAL_APPROVE,
    Permission.SERVICE_ORDER_APPROVAL_REJECT,
    Permission.SERVICE_ORDER_CREATE,
    Permission.SERVICE_ORDER_START,
    Permission.SERVICE_ORDER_DIAGNOSE,
    Permission.SERVICE_ORDER_COMPLETE,
    Permission.SERVICE_ORDER_CANCEL,
    Permission.STOCK_VIEW,
    Permission.STOCK_UPDATE,
    Permission.FINANCIAL_VIEW,
    Permission.AUDIT_VIEW,
    Permission.USER_MANAGE,
    Permission.SERVICE_ORDER_EXECUTION_VIEW,
    Permission.SERVICE_ORDER_EXECUTION_ASSIGN,
    Permission.SERVICE_ORDER_EXECUTION_START,
    Permission.SERVICE_ORDER_EXECUTION_PAUSE,
    Permission.SERVICE_ORDER_EXECUTION_RESUME,
    Permission.SERVICE_ORDER_EXECUTION_COMPLETE,
    Permission.SERVICE_ORDER_STOCK_VIEW,
    Permission.SERVICE_ORDER_STOCK_CONSUME,
  ],

  [Role.MECHANIC]: [
    Permission.SERVICE_ORDER_VIEW,
    Permission.SERVICE_ORDER_ITEM_VIEW,
    Permission.SERVICE_ORDER_ITEM_ADD,
    Permission.SERVICE_ORDER_ITEM_UPDATE,
    Permission.SERVICE_ORDER_ITEM_REMOVE,
    Permission.SERVICE_ORDER_APPROVAL_VIEW,
    Permission.SERVICE_ORDER_START,
    Permission.SERVICE_ORDER_DIAGNOSE,
    Permission.SERVICE_ORDER_COMPLETE,
    Permission.STOCK_VIEW,
    Permission.SERVICE_ORDER_EXECUTION_VIEW,
    Permission.SERVICE_ORDER_EXECUTION_START,
    Permission.SERVICE_ORDER_EXECUTION_PAUSE,
    Permission.SERVICE_ORDER_EXECUTION_RESUME,
    Permission.SERVICE_ORDER_EXECUTION_COMPLETE,
    Permission.SERVICE_ORDER_STOCK_VIEW,
    Permission.SERVICE_ORDER_STOCK_CONSUME,
  ],

  [Role.FINANCIAL]: [
    Permission.SERVICE_ORDER_VIEW,
    Permission.SERVICE_ORDER_ITEM_VIEW,
    Permission.SERVICE_ORDER_APPROVAL_VIEW,
    Permission.FINANCIAL_VIEW,
    Permission.FINANCIAL_CREATE,
    Permission.AUDIT_VIEW,
    Permission.SERVICE_ORDER_EXECUTION_VIEW,
    Permission.SERVICE_ORDER_STOCK_VIEW,
  ],

  [Role.ATTENDANT]: [
    Permission.SERVICE_ORDER_VIEW,
    Permission.SERVICE_ORDER_ITEM_VIEW,
    Permission.SERVICE_ORDER_ITEM_ADD,
    Permission.SERVICE_ORDER_ITEM_UPDATE,
    Permission.SERVICE_ORDER_ITEM_REMOVE,
    Permission.SERVICE_ORDER_APPROVAL_VIEW,
    Permission.SERVICE_ORDER_APPROVAL_REQUEST,
    Permission.SERVICE_ORDER_CREATE,
    Permission.STOCK_VIEW,
    Permission.SERVICE_ORDER_EXECUTION_VIEW,
    Permission.SERVICE_ORDER_STOCK_VIEW,
  ],

  [Role.STOCKIST]: [
    Permission.SERVICE_ORDER_ITEM_VIEW,
    Permission.SERVICE_ORDER_APPROVAL_VIEW,
    Permission.STOCK_VIEW,
    Permission.STOCK_UPDATE,
    Permission.SERVICE_ORDER_EXECUTION_VIEW,
    Permission.SERVICE_ORDER_STOCK_VIEW,
    Permission.SERVICE_ORDER_STOCK_CONSUME,
  ],
};
